#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting motion domain)
path=$(sudo yunohost app setting motion path)

# Remove trailing "/" for next commands
path=${path%/}

# Upgrade official debian package
sudo apt-get update
sudo apt-get upgrade motion -y

# Update and reload Nginx
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/motion.conf
sudo service nginx reload

sudo yunohost app ssowatconf

echo $?
